### ISSUE TITLE
How to setup Bedrock trust policy

### ISSUE THREAD

**Issue by nicolamassarenti** [aws-samples/multi-account-bedrock-llm-streaming#2]
Hi @raymlai8,

I'm trying to replicate a similar setup but I'm having issues in creating a trust policy between the accounts.

Can you add more details about the IAM setup?

**Comment by nicolamassarenti** [comment]
FYI the accounts are under the same organization

**Comment by raymlai8** [comment]
added the assume role and trust relationships settings required for both accounts inside readme.md under [advance-setup-privatelink-vpc]
